version: '3.8'

services:

  vinted-discord-bot:
    image: test-vinted
    environment:
      VINTED_BOT_ADMIN_IDS: "317636589897515009"
      VINTED_BOT_TOKEN: "MTA2MzQwNTExNzU2ODcyOTE0OA.Ga7-8_.SZh4DuRlx4fLhn0c7l8LkhCcZQio4ljFhOF4XA"
      POSTGRES_DB: vinted_bot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external:
      name: bot-HYPER
